In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.datasets import load_iris

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score


In [5]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [26]:
iris = load_iris()

In [27]:
l_scores = cross_val_score(LogisticRegression(max_iter=1000), iris.data, iris.target,cv=10)
l_scores

array([1.        , 0.93333333, 1.        , 1.        , 0.93333333,
       0.93333333, 0.93333333, 1.        , 1.        , 1.        ])

In [28]:
np.average(l_scores)

np.float64(0.9733333333333334)

In [29]:
d_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target, cv=10)
d_scores

array([1.        , 0.93333333, 1.        , 0.93333333, 0.93333333,
       0.86666667, 0.93333333, 0.93333333, 1.        , 1.        ])

In [30]:
np.average(d_scores)

np.float64(0.9533333333333334)

In [31]:
s_scores = cross_val_score(SVC(), iris.data, iris.target, cv=10)
s_scores

array([1.        , 0.93333333, 1.        , 1.        , 1.        ,
       0.93333333, 0.93333333, 0.93333333, 1.        , 1.        ])

In [32]:
np.average(s_scores)

np.float64(0.9733333333333334)

In [33]:
r_scores = cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target, cv=10)
r_scores

array([1.        , 0.93333333, 1.        , 0.93333333, 0.93333333,
       0.93333333, 0.93333333, 0.93333333, 1.        , 1.        ])

In [34]:
np.average(r_scores)

np.float64(0.96)